spring:
  # dev-开发环境
  #  profiles.active: dev

  # 豹子-快趣付
  #  profiles.active: quickpay.live

  # 林宇-迪拜支付
  #  profiles.active: dibaipay.com

  # 阿华-快付通
  #  profiles.active: quickpay.ink

  # 王总-佩绮支付
  #  profiles.active: paych.vip

  # 小哥哥-柬埔支付
  profiles.active: ynztqp.cn

  thymeleaf:
    cache: false
    prefix: classpath:/template/
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10
        max-concurrency: 50
        prefetch: 5
  cache.type: redis
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
  datasource:
    username: root
    password: yatuier95.
    url: jdbc:mysql://localhost:3306/pay?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #druid连接池的信息配置
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 5
      #最大值
      maxActive: 5000
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 14400000
      #配置一个连接在池中最长生存的时间
      maxEvictableIdleTimeMillis: 28800000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall
      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置StatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #允许那些ip
        allow: 127.0.0.1
        login-username: admin
        login-password: yatuier95.
        #禁止那些ip
        deny:
        #是否可以重置
        reset-enable: true
        #启用
        enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8080
  tomcat.uri-encoding: utf-8

logging.config: classpath:logback-prod.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml

application:
  juhe:
    qrcode:
      key: 09a17ca5b1c432b333a8b2b121f665b7